name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Ejecutar tests con cobertura
        run: |
          pytest --cov=core/application --cov-report=term-missing

      - name: Subir reporte de cobertura (opcional)
        if: success()
        run: echo "Tests completados con éxito"
